Reporting: Time Connected Summary
xibosignage/xibo-cms pull request #1779
Opened 2023-05-05 10:04 UTC by ifarzana

- Fixes https://github.com/xibosignage/xibo/issues/3043

2023-05-05 10:05 UTC, ifarzana commented
@dasgarner, Can you check if I can refactor the `$displaySql`?

2023-05-05 16:04 UTC, dasgarner reviewed
I think the main query is the displays query, and that the disconnected displays query can be simplified to just a list of events with displayId (no need to add tags, etc to that).

2023-05-05 16:04 UTC, dasgarner commented on lib/Report/TimeDisconnectedSummary.php
> +        $displaySql = $displaySelect . $displayBody;
Since we removed paging, we don't need to separate the displaySelect and displayBody - the whole query can just be displaySql.

2023-05-09 10:11 UTC, dasgarner requested changes

2023-05-09 10:11 UTC, dasgarner commented on lib/Report/TimeDisconnectedSummary.php
> +        foreach ($this->store->select($displaySql, $params) as $displayRow) {
Doing two loops means that the sorting is broken? 

You should only add to `$rows` in this loop, and always pull in the time disconnected/connected from the `$disconnectedDisplays` array.

2023-05-09 12:54 UTC, dasgarner approved these changes

2023-05-09 12:56 UTC, merged