Translations from the config XML files
xibosignage/xibo-cms pull request #1818
Opened 2023-05-24 12:04 UTC by ifarzana

- Related to https://github.com/xibosignageltd/xibo-private/issues/183

2023-05-24 12:06 UTC, ifarzana commented
@dasgarner I am getting an error `PHP Fatal error:  Uncaught LogicException: Unable to register extension "Slim\Views\TwigExtension" as it is already registered. in /var/www/cms/vendor/twig/twig/src/ExtensionSet.php:132
Stack trace:` 

Do you see anything that I am not doing correctly?

2023-05-24 12:32 UTC, dasgarner commented
I don't think creating the whole application stack is the right way to pursue this. We discussed creating the ModuleFactory and ModuleTemplateFactory manually instead?

To do that you'd need to use `new ModuleFactory()` and supply mocked objects for its dependencies.

I think this would be workable because the bit we want (the XML parsing) doesn't rely on any of those dependencies (I think)

2023-05-25 15:29 UTC, dasgarner requested changes
Looks like you've cracked it - just a few suggestions.

2023-05-25 15:29 UTC, dasgarner commented on bin/locale.php
>   * Copyright (C) 2019 Xibo Signage Ltd
Odd that this copyright didn't update? is the profile setup in your IDE?

2023-05-25 15:29 UTC, dasgarner commented on bin/locale.php
> +if (!file_exists(PROJECT_ROOT . '/web/settings.php')) {
I don't think we need this?

2023-05-25 15:29 UTC, dasgarner commented on bin/locale.php
> +// Transactor funtion
```suggestion
// Translator function
```

2023-05-25 15:29 UTC, dasgarner commented on bin/locale.php
> +if (!file_exists($file)) {
I don't think you need to do this - file_put_contents will create a file if it doesn't exist and overwrite one if it does.

2023-05-25 15:29 UTC, dasgarner commented on bin/locale.php
> +        foreach ($module->properties as $property) {
Sorry, I did add another requirement regarding parsing a rule message :smile:

2023-05-26 08:35 UTC, dasgarner approved these changes
Looks good!

2023-05-26 08:38 UTC, merged