Elements: Stocks
xibosignage/xibo-cms pull request #1875
Opened 2023-06-20 07:47 UTC by rubenpingol-xibo

resolves xibosignageltd/xibo-private#296

2023-06-20 07:54 UTC, dasgarner requested changes
I have a few bits I am confused about

2023-06-26 08:37 UTC, maurofmferrao approved these changes
Looks good to me!

2023-06-26 08:50 UTC, maurofmferrao approved these changes

2023-06-26 09:14 UTC, dasgarner approved these changes

2023-06-26 11:43 UTC, merged