Layout Editor: Avoid too many viewer refreshes
xibosignage/xibo-cms pull request #2220
Opened 2023-11-10 16:05 UTC by maurofmferrao

relates to xibosignageltd/xibo-private#547

2023-11-10 16:56 UTC, dasgarner requested changes
Making sure I am paying attention eh? 😄

2023-11-10 16:56 UTC, dasgarner commented on ui/src/editor-core/widget.js
> +          debugger;
I don't think you want this in here...

2023-11-13 08:31 UTC, dasgarner approved these changes

2023-11-13 08:50 UTC, maurofmferrao commented
TEST: *

2023-11-13 08:52 UTC, maurofmferrao commented
TEST: * END

2023-11-13 09:21 UTC, maurofmferrao commented
TEST: layout_designer_empty.cy.js, layout_designer_populated_unchanged.cy.js, layout_designer_populated.cy.js END

2023-11-13 09:47 UTC, merged