Stocks and Currency stencils
xibosignage/xibo-cms pull request #2607
Opened 2024-07-04 12:34 UTC by maurofmferrao

relates to xibosignageltd/xibo-private#769

2024-07-05 14:04 UTC, dasgarner requested changes

2024-07-05 14:04 UTC, dasgarner commented on modules/assets/template-thumbnails/currency/elements/stocks1.xcf
Should this file be here?

2024-07-05 14:11 UTC, maurofmferrao commented on modules/assets/template-thumbnails/currency/elements/stocks1.xcf
Good catch, that was a file from Gimp to create the thumbnails. 🤦🏻 I'm going to remove it on another commit.

2024-07-07 20:36 UTC, dasgarner approved these changes

2024-07-10 13:08 UTC, gracec20 commented
TEST: /Layout END

2024-07-11 08:11 UTC, merged