Report: Add Session History
xibosignage/xibo-cms pull request #2642
Opened 2024-07-17 09:45 UTC by mgbaybay

## Changes:
- Added `session` option and `session history table` in Sessions report 

Relates to: https://github.com/xibosignageltd/xibo-private/issues/747

2024-07-17 10:51 UTC, dasgarner requested changes
The report looks good! There are some structure changes I think we need to look at.

2024-07-17 10:51 UTC, dasgarner commented on lib/Report/SessionHistory.php
> +                $endTime = isset($row['session_expiration']) ? date("Y-m-d H:i:s", $row['session_expiration']) : null;
There are some stray `"` here.

Also it would be better to use the `getSystemFormat` function in DateFormatHelper

2024-07-17 10:51 UTC, dasgarner commented on lib/Report/SessionHistory.php
> +                        LIKE CONCAT("sessionHistoryId|i:", session_history.sessionId, "%")
Needing to do this sort of join points to a data model problem, it also means that as the sessions are removed from the session table, we lose the `session_expiration` and therefore the end date and duration from the report.

Ideally we would have a `lastUsedTime` field in the session_history table which is updated each time an existing session is touched, and would then accurately represent the time that session was active.

That is outside the scope of the initial issue, but please you could investigate adding this column to the table and making sure it gets updated when the session is accessed?

2024-07-17 14:15 UTC, dasgarner approved these changes

2024-07-19 12:18 UTC, ifarzana approved these changes

2024-07-19 13:48 UTC, ifarzana commented
TEST: /Reporting END

2024-07-22 07:27 UTC, merged