DataSet: trying to import without any columns logs an unhelpful error
xibosignage/xibo-cms pull request #2665
Opened 2024-07-31 05:57 UTC by nadzpogi

relates to xibosignage/xibo#3458

2024-07-31 09:25 UTC, PeterMis requested changes
I think this looks fine for manual csv import, however looking at the issue it should also cover remote datasets.

ie processing json/csv from remote dataSet source should also check for no columns - in this case perhaps also conditionally for no `remote` columns.

The message on the form could also be adjusted for remote dataSet to check the remote columns - the message for no columns at all that you have is fine, but in case of the remote dataSet we are more interested in remote columns instead.

2024-08-01 11:51 UTC, PeterMis reviewed
Looks good to me, just a very minor comments below.

2024-08-01 11:51 UTC, PeterMis commented on lib/Helper/DataSetUploadHandler.php
> +                return $column->dataSetColumnType == 'Value';
Might be better to rely on `dataSetColumnTypeId` instead? ( result should be the same )

2024-08-01 11:51 UTC, PeterMis commented on lib/Helper/DataSetUploadHandler.php
> +                throw new InvalidArgumentException('Import failed: No value columns defined in the dataset.');
Should we translate the exception message?

2024-08-01 11:51 UTC, PeterMis commented on lib/XTR/RemoteDataSetFetchTask.php
> +                    return $column->dataSetColumnType == 'Remote';
Similar to previous comment, perhaps rely on `dataSetColumnTypeId` ?

2024-08-01 13:04 UTC, PeterMis approved these changes

2024-08-06 13:50 UTC, ifarzana commented
TEST: /Administration END

2024-08-07 03:39 UTC, merged