Display: Fix for updating detail of an alert when submitting the end
xibosignage/xibo-cms pull request #2714
Opened 2024-08-23 07:57 UTC by mgbaybay

## Changes
- Display: Update detail of an alert when submitting the end

Relates to: https://github.com/xibosignage/xibo/issues/3478

2024-08-23 12:53 UTC, dasgarner requested changes

2024-08-23 12:53 UTC, dasgarner commented on lib/Xmds/Soap.php
> +                : $displayEvent->eventEndByReference($this->display->displayId, $eventTypeId, $refId, $detail);
Is it possible to also do it if there is no reference?

2024-08-23 12:53 UTC, dasgarner commented on lib/Entity/DisplayEvent.php
> +                      `detail` = CONCAT_WS(". ", NULLIF(CONCAT_WS(".", NULLIF(`detail`, "")), ""), :detail)
Can we use single quotes for consistency?

2024-08-23 12:53 UTC, dasgarner commented on lib/Entity/DisplayEvent.php
> +                      `detail` = CONCAT_WS(". ", NULLIF(CONCAT_WS(".", NULLIF(`detail`, "")), ""), :detail)
Also can you explain why the double concat_ws in a comment so its easy to refer to later?

2024-08-27 07:28 UTC, dasgarner approved these changes

2024-08-28 15:18 UTC, ifarzana commented
TEST: /Display END

2024-08-28 16:33 UTC, merged