Emergency Alerts & Messages (Common Alert Protocol)
xibosignage/xibo-cms pull request #2728
Opened 2024-09-03 11:12 UTC by nadzpogi

relates to xibosignageltd/xibo-private#833

2024-09-04 08:29 UTC, dasgarner requested changes

2024-09-04 08:29 UTC, dasgarner commented on modules/emergency-alert.xml
> +<module>
We should define a cacheKey which has the displayId in it, because we know that alerts should be display specific

2024-09-04 08:29 UTC, dasgarner commented on lib/Connector/CapConnector.php
> +                ->addMetric('status', __('Status'))
Should we make these more specific to avoid conflicts with other criteria metrics?

2024-09-04 08:29 UTC, dasgarner commented on lib/Connector/CapConnector.php
> +        $event->addType('emergency_alerts', __('Emergency Alerts'))
Are we missing `isEmergencyAlertActive` ?

2024-09-09 06:57 UTC, dasgarner commented on lib/Connector/CapConnector.php
> +                throw new GeneralException('Failed to retrieve CAP data from the specified URL.');
Should we surface this error into the layout editor using `->addError()` ?

2024-09-09 06:57 UTC, dasgarner commented on lib/Connector/CapConnector.php
> +        $emergencyAlertUrl = $dataProvider->getProperty('emergencyAlertUri');
It would be good to handle the case where the user hasn't entered the URL

2024-09-12 07:16 UTC, dasgarner approved these changes

2024-09-16 07:59 UTC, dasgarner approved these changes

2024-09-26 11:27 UTC, dasgarner approved these changes

2024-09-27 07:45 UTC, ifarzana commented
TEST: login.cy.js END

2024-10-02 10:35 UTC, maurofmferrao approved these changes

2024-10-02 10:50 UTC, merged