Schedule Criteria: weather "clear sky" condition does not match
xibosignage/xibo-cms pull request #2740
Opened 2024-09-18 10:33 UTC by nadzpogi

relates to xibosignage/xibo#3487

- Modified metric IDs to better align with JSON responses from the OWM API.
- Added a prefix to avoid conflicts with other potential weather schedule criteria.
- Removed metrics that are not present in OpenWeather API responses.

2024-09-19 11:10 UTC, PeterMis submitted a review, later dismissed

2024-09-20 07:05 UTC, PeterMis submitted a review, later dismissed

2024-10-01 10:11 UTC, dasgarner requested changes
The OWM prefix doesn't make sense - criteria should be service agnostic so a prefix of `weather_` would make more sense.

2024-10-01 11:29 UTC, dasgarner approved these changes

2024-10-02 08:13 UTC, dasgarner approved these changes

2024-10-02 09:47 UTC, ifarzana commented
TEST: /Schedule END

2024-10-02 10:33 UTC, merged