Reports: Add Proof of Play MongoDB grouping
xibosignage/xibo-cms pull request #2748
Opened 2024-09-25 19:17 UTC by mgbaybay

## Changes
FE:
- Fixed column duration column calculation

BE:
- [MongoDB] Added data calculation for accumulating the values according to grouping option

Relates to: https://github.com/xibosignage/xibo/issues/3356

2024-09-27 07:17 UTC, dasgarner requested changes

2024-09-27 07:17 UTC, dasgarner commented on lib/Report/ProofOfPlay.php
> +            foreach ($this->displayGroupFactory->query(null, ['displayId' => $row['displayId']]) as $dg) {
Should we consider caching the display somewhere so that we don't hit the database for each stat record?

2024-09-27 07:17 UTC, dasgarner commented on lib/Report/ProofOfPlay.php
> +                if (!$displayIds || in_array($dg->displayGroupId, $displayIds)) {
We're checking here whether the displayGroupId is in an array of displayIds (for filtering purposes), but will that ever be true?

2024-09-27 07:17 UTC, dasgarner commented on lib/Report/ProofOfPlay.php
> +        foreach ($this->tagFactory->query() as $tag) {
This is always looking at all possible tags, which feels like it could be optimised, but I am not sure why we look for them all?

2024-10-01 07:11 UTC, dasgarner approved these changes

2024-10-02 10:44 UTC, ifarzana commented
TEST: /Reporting END

2024-10-02 10:59 UTC, merged